<ul class="header__navbar-list hide-on-mobi show-on-pc-flex">
    <li class="header__navbar-item header__navbar-separate">
        <a href="" class="header__navbar-item-link header-active-2">De</a>
    </li>
    <li class="header__navbar-item header__navbar-separate">
        <a href="" class="header__navbar-item-link">Fr</a>
    </li>
    <li class="header__navbar-item">
        <a href="" class="header__navbar-item-link">It</a>
    </li>                     
</ul>             

    
<ul class="header__mobile-list">
    <li class="header__mobile-item hide-on-mobi show-on-pc">
        <img src="<?php echo $block->getUrl("media/images/")?>search.png" /> 
       
    </li>
    <li class="header__mobile-item hide-on-mobi show-on-pc">
        <img src="<?php echo $block->getUrl("media/images/")?>acc.png" /> 
    </li>
    <li class="header__mobile-item">
        <img src="<?php echo $block->getUrl("media/images/")?>heart.png" />            
    </li>
    <li class="header__mobile-item">
        <img src="<?php echo $block->getUrl("media/images/")?>cart.png" /> 
        
    </li>
</ul>
<div class="header__content js-modal-1">
    <div class="header__menu">
        <div class="header__navbar hide-on-pc">
            <ul class="header__navbar-list">
                <li class="header__navbar-item header__navbar-first">
                    <a href="" class="header__navbar-item-link ">
                        <img src="<?php echo $block->getUrl("media/images/")?>acc.png" /> 
                    </a>
                </li>
                <li class="header__navbar-item ">
                    <a href="" class="header__navbar-item-link header__navbar-active-1">
                        My account
                    </a>
                </li>
            </ul>
            <ul class="header__navbar-list">
                <li class="header__navbar-item header__navbar-separate">
                    <a href="" class="header__navbar-item-link header-active-2">De</a>
                </li>
                <li class="header__navbar-item header__navbar-separate">
                    <a href="" class="header__navbar-item-link">Fr</a>
                </li>
                <li class="header__navbar-item">
                    <a href="" class="header__navbar-item-link">It</a>
                </li>
              
            </ul>
            <ul class="header__navbar-list">
                <li class="header__navbar-item header-icon ">  
                    <img src="<?php echo $block->getUrl("media/images/")?>close.png" class="img-icon js-close-1" /> 
                </li>
            </ul>
        </div> 
        <div class="header__category">
            <ul class=" header__category-list">
                <li class="header__category-item">
                    <a href="" class="header__category-item-link header-active-2">
                        <p>Your</p>
                        Jewelry                                        
                    </a>
                </li>
                <li class="header__category-item">
                    <a href="" class="header__category-item-link">Engagement &amp; Wedding</a>
                </li>
                <li class="header__category-item">
                    <a href="" class="header__category-item-link">Fashion &amp; More...</a>
                </li>                                 
            </ul>
           
        </div> 
    </div> 
    <div class="header__firstmenu">
        <ul class="header__firstmenu-list">
            <li class="header__firstmenu-item js-action ">
                Men          
                <img src="<?php echo $block->getUrl("media/images/")?>arrow-right.png" />                                               
            </li>
            <li class="header__firstmenu-item">
                Women  
                <img src="<?php echo $block->getUrl("media/images/")?>arrow-right.png" />                                                                                                       
            </li>
            <li class="header__firstmenu-item">
                Kids
                <img src="<?php echo $block->getUrl("media/images/")?>arrow-right.png" />                                                                                                                      
            </li>
            <li class="header__firstmenu-item">
                News
                <img src="<?php echo $block->getUrl("media/images/")?>arrow-right.png" />                                                                                         
            </li> 
            <li class="header__firstmenu-item">
                Style
                <img src="<?php echo $block->getUrl("media/images/")?>arrow-right.png" />                                                                                                          
            </li>            
        </ul>  
        <a href="" class="header__firstmenu-logout-link">
            <img src="<?php echo $block->getUrl("media/images/")?>logout.png" /> 
            Logout
        </a>        
    </div> 
    <div class="header__modal js-modal ">
        <div class="header__secondmenu">
            <div class="header__secondmenu-title ">
                <img src="<?php echo $block->getUrl("media/images/")?>arrow-left.png" />                                     
                Men
                <img src="<?php echo $block->getUrl("media/images/")?>close.png"  class="js-close"/>                              
            </div>
            <div class="header__secondmenu-service">
                <div class="grid ">
                    <h2 class="header__secondmenu-content">Services</h2>
                    <ul class="header__secondmenu-list">
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Ring sizing
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Free engraving
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Lifetime waranty
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Jewellery protection plans
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Free insured shipping
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Online returns
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Free gift packaging
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Gift certificate
                            </li>
                        </a>
                    </ul>
                    <h2 class="header__secondmenu-content">Another Category</h2>
                    <ul class="header__secondmenu-list">
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Ring sizing
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Free engraving
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Lifetime waranty
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Jewellery protection plans
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Free insured shipping
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Online returns
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Free gift packaging
                            </li>
                        </a>
                        <a href="" class="header__secondmenu-link">
                            <li class="header__secondmenu-item">
                                Gift certificate
                            </li>
                        </a>
                    </ul>
    
                </div>
                
            </div>
        </div>
    </div>
</div>

