<ul class="header__submenu-list">
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            rings
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            necklaces
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            earings
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            Brooches
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            anklets
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            nose pins
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            men
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            women
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            kids
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            couple
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            collections
        </a>
    </li>
</ul>

<script>
    const actionMenus = document.querySelectorAll('.js-action')
const modal = document.querySelector('.js-modal')
const closes = document.querySelectorAll('.js-close')
function showMenu() {
    modal.classList.add('header__modal-open')
}
function hideMenu() {
    modal.classList.remove('header__modal-open')
}
for (const actionMenu of actionMenus) {
    actionMenu.addEventListener('click', showMenu)
}
for ( const close of closes) {
    close.addEventListener('click', hideMenu)
}


const actionHeaders = document.querySelector('.js-action-1')
const model = document.querySelector('.js-modal-1')
const exits = document.querySelector('.js-close-1')
function showHeader() {
    model.classList.add('header__content-open')

}
function hideHeader() {
    model.classList.remove('header__content-open')
} 

actionHeaders.addEventListener('click', showHeader)

exits.addEventListener('click', hideHeader)

</script>
